#
# Adder library
#

load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "adder",
    srcs = [
        "adder.cpp",
    ],
    hdrs = [
        "adder.hpp",
    ],
    visibility = [
        "//test:__subpackages__",
    ],
)
